### ISSUE TITLE
1.29 support ?

### ISSUE THREAD

**Issue by albert-kam** [leonardodino/wc3proxy#4]
Hi, does it support 1.29 version ? My binary wc3proxy currently supports until 1.28 only, which is uncool considering the widescreen support from 1.29.

Thanks !

**Comment by leonardodino** [comment]
should work! 😄 

It just defaults to the 1.28 version, but it's not hardcoded, [the CLI receives a parameter](https://github.com/leonardodino/wc3proxy/blob/main/cli/MainProxy.cs#L54).

**Comment by albert-kam** [comment]
Dear Lenoardodino,

Super sorry for the late reply.
Havent tried this out, but thanks so much for the quick reply. 
I will try this and will report whether it's a success or not.

Take care !
Bert
